name: Build Kernel
on:
  workflow_dispatch:
    inputs:
      REPO:
        description: 'Kernel repository'
        default: 'slakkystar/Xiaomi-chime'
        required: true
      BRANCH:
        description: 'Kernel branch'
        default: 'lime-q-oss'
        required: true
      DEVICE_TARGET:
        description: 'Device to build'
        type: string
        default: 'chime'
        required: true
      KCFLAGS_W:
        description: 'Enable KCFLAGS=-w'
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    steps:
    - name: Set Timezone
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update && apt-get install -y tzdata
        ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Prepare Dependencies
      run: chmod +x ./build.sh && bash ./build.sh --setup-deps

    - name: Clone kernel source
      run: git clone --single-branch -b ${{ inputs.BRANCH }} https://github.com/${{ inputs.REPO }} kernel_root

    - name: Cache Toolchains
      id: cache-toolchain
      uses: actions/cache@v4
      with:
        path: /tmp/toolchains
        key: toolchain-clang10.0.7-gcc4.9-v1

    - name: Cache ccache
      uses: actions/cache@v4
      with:
        path: ~/.ccache
        key: ccache-kernel-${{ github.sha }}
        restore-keys: |
          ccache-kernel-

    - name: Fetch Toolchains
      if: steps.cache-toolchain.outputs.cache-hit != 'true'
      run: bash ./build.sh --fetch-toolchains

    - name: Build Kernel
      env:
        DEVICE_TARGET: ${{ inputs.DEVICE_TARGET }}
        KCFLAGS_W: "${{ inputs.KCFLAGS_W }}"
        CCACHE_SIZE: "7.5G"
        CLEAN_BUILD: "false"
      run: |
        mkdir -p ~/.ccache
        cd kernel_root
        bash ../build.sh

    - name: Upload kernel artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Kernel-${{ inputs.DEVICE_TARGET }}
        include-hidden-files: true
        if-no-files-found: ignore
        path: |
          kernel_root/*.zip
          kernel_root/out/.config
