name: Build Kernel
on:
  workflow_dispatch:
    inputs:
      REPO:
        description: 'Kernel repository'
        default: 'slakkystar/kernel_xiaomi_citrus_sm6115'
        required: true
      BRANCH:
        description: 'Kernel branch'
        default: 'android16'
        required: true
      DEVICE_TARGET:
        description: 'Device to build'
        type: string
        default: 'chime'
        required: true
      RSU:
        description: 'Add ReSukiSU support'
        type: boolean
        default: true
      SUSFS:
        description: 'Add SuSFS support'
        type: boolean
        default: true
      APPLY_WORKAROUND:
        description: 'Disable Thermal Configs'
        type: boolean
        default: false
      BUILD_RELEASE:
        description: 'Build non-nightly'
        type: boolean
        default: false
      UPDATE_TOOLCHAIN:
        description: 'Force update toolchain cache'
        type: boolean
        default: false
      KCFLAGS_W:
        description: 'Enable KCFLAGS=-w'
        type: boolean
        default: true
      TOOLCHAIN_URL:
        description: 'Custom Clang toolchain URL (leave empty for default)'
        required: false
        default: ''
      UPLOAD_RELEASE:
        description: 'Upload final zip to GitHub Releases'
        type: boolean
        default: false
      ANDROID_VER:
        description: 'Type custom Android version for localversion'
        type: string
        default: 'android16'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set Timezone
      run: sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

    - uses: actions/checkout@v5
      with:
        fetch-depth: 1

    - name: Clone kernel source
      if: inputs.UPDATE_TOOLCHAIN != 'true'
      run: git clone --single-branch -b ${{ inputs.BRANCH }} https://github.com/${{ inputs.REPO }} kernel_root

    - name: Cache Toolchain
      id: cache-toolchain
      uses: actions/cache@v5
      with:
        path: ~/clang-22
        key: llvm-22-${{ hashFiles('**/TOOLCHAIN_URL') || 'default' }}

    - name: Cache ccache
      uses: actions/cache@v5
      with:
        path: ~/.ccache
        key: ccache-kernel-${{ github.sha }}
        restore-keys: ccache-kernel-

    - name: Prepare Dependencies
      run: chmod +x ./build.sh && bash ./build.sh --setup-deps

    - name: Setup Build Environment
      if: inputs.UPDATE_TOOLCHAIN != 'true'
      id: buildKernel
      run: |
        cd kernel_root
        KERNELCODE=$(cat ../codename 2>/dev/null || echo "kernel")
        echo "KERNELCODE=$KERNELCODE" >> $GITHUB_ENV

    - name: Fetch Toolchains
      if: steps.cache-toolchain.outputs.cache-hit != 'true' || inputs.UPDATE_TOOLCHAIN == 'true'
      env:
        UPDATE_TOOLCHAINS: ${{ inputs.UPDATE_TOOLCHAIN }}
        TOOLCHAIN_URL: ${{ inputs.TOOLCHAIN_URL }}
      run: bash ./build.sh --fetch-toolchains

    - name: Build Kernel
      if: inputs.UPDATE_TOOLCHAIN != 'true'
      env:
        DEVICE_TARGET: ${{ inputs.DEVICE_TARGET }}
        APPLY_WORKAROUND: ${{ inputs.APPLY_WORKAROUND }}
        RSU: ${{ inputs.RSU }}
        SUSFS: ${{ inputs.SUSFS }}
        KCFLAGS_W: "${{ inputs.KCFLAGS_W }}"
        TOOLCHAIN_URL: "${{ inputs.TOOLCHAIN_URL }}"
        CCACHE_SIZE: "7.5G"
        CLEAN_BUILD: "false"
        ANDROID_VER: "${{ inputs.ANDROID_VER }}"
      run: |
        if [ ! -d ~/.ccache ]; then
          mkdir -p ~/.ccache
        fi

        cd kernel_root

        if [[ "$RSU" == "true" ]]; then
          export IS_RSU_ENABLED=true
          curl -LSs "https://raw.githubusercontent.com/slakkystar/ReSukiSU/refs/heads/master/kernel/setup.sh" | bash -s master
          
          PATCH_FILE="../scope-minimized-manual-hooks-v2.2.patch"
          if [ -f "$PATCH_FILE" ]; then
            echo "Applying $PATCH_FILE..."
            git apply "$PATCH_FILE" || patch -p1 < "$PATCH_FILE"
          else
            echo "Warning: Patch file $PATCH_FILE not found!"
          fi
        fi

        bash ../build.sh

    - name: Upload kernel artifacts
      if: always()
      uses: actions/upload-artifact@v5
      with:
        name: Kernel-${{ inputs.DEVICE_TARGET }}
        include-hidden-files: true
        if-no-files-found: ignore
        path: |
          kernel_root/*.zip
          kernel_root/out/.config

    - name: Upload to GitHub Release
      if: inputs.UPLOAD_RELEASE == 'true' && inputs.UPDATE_TOOLCHAIN != 'true'
      uses: softprops/action-gh-release@v2
      with:
        files: kernel_root/*.zip
        tag_name: "build-${{ github.run_number }}"
        name: "Kernel Build #${{ github.run_number }}"
        draft: false
        prerelease: ${{ inputs.BUILD_RELEASE == 'false' }}
